name: paritta_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^19.2.0
  flutter_localizations:
    sdk: flutter
  flutter_settings_ui: ^3.0.1
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  google_fonts: ^6.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  lunar: ^1.7.4
  markdown_widget: ^2.3.2+6
  provider: ^6.1.4
  settings_ui: ^2.0.2
  shared_preferences: ^2.5.3
  sliver_tools: ^0.2.12
  timezone: ^0.10.1
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  flutter_autostart: ^0.0.2
  device_info_plus: ^11.4.0
  mockito: ^5.5.0

dev_dependencies:
  bloc_test: ^10.0.0
  bloc_lint: ^0.2.0-dev
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freeze: ^1.0.0
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/markdown/paritta/
    - assets/json/menu/
    - assets/json/
    - assets/images/